Add addToRecipesToCook method and some sad path tests in user-test
sme93/refactor-tractor pull request #41
Opened 2021-04-14 01:15 UTC by sme93

# Pull Request Template
## Description
Please include a summary of the change and which issue is fixed. Add recipesToCook/addToRecipesToCook method and tests, sad path testing in User and User Class

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2021-04-14 14:42 UTC, mcraig2342 requested changes
The only change I would make is adding that new User instantiation into the before each, other than that it looks good!

2021-04-14 14:42 UTC, mcraig2342 commented on test/user-test.js
> -    pantry = [{
Couldn't we just add const user = new User(id, username) to the before each so we don't have to write it before every test. I know you hate before each lol but I think it makes a lot of sense in this case

2021-04-14 14:42 UTC, mcraig2342 commented on src/user.js
> +    }
looks good!

2021-04-15 01:09 UTC, sarahlane8 approved these changes
Looks great! Like the syntax changes.  
I see that you took off the pantry property on the user.  We may want to consider adding it back in later, when we see how the Pantry Class develops.  We will have to see!

2021-04-15 01:11 UTC, merged